import {
  Waves,
  Sun,
  Footprints,
  Bike,
  Gem,
  Anchor,
  Building2,
  Sparkles,
  Users,
  Compass,
  TrendingUp,
  Landmark,
  Square,
  Triangle,
  ShoppingBag,
  Leaf,
  Globe,
  Lightbulb,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  waves: Waves,
  sun: Sun,
  footprints: Footprints,
  bike: Bike,
  gem: Gem,
  anchor: Anchor,
  "building-2": Building2,
  sparkles: Sparkles,
  users: Users,
  compass: Compass,
  "trending-up": TrendingUp,
  landmark: Landmark,
  square: Square,
  triangle: Triangle,
  "shopping-bag": ShoppingBag,
  leaf: Leaf,
  globe: Globe,
  lightbulb: Lightbulb,
};
